# Generated by Django 5.2.1 on 2025-06-23 09:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='사용자 ID')),
                ('password', models.CharField(max_length=255, verbose_name='비밀번호')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('birth_date', models.DateField(verbose_name='생년월일')),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성'), ('O', '기타')], max_length=1, verbose_name='성별')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('bias_group', models.CharField(blank=True, choices=[('BLACKPINK', 'BLACKPINK'), ('aespa', 'aespa'), ('IVE', 'IVE'), ('GIDLE', '(G)I-DLE'), ('TWICE', 'TWICE'), ('NEWJEANS', 'NewJeans'), ('RED_VELVET', 'Red Velvet'), ('LE_SSERAFIM', 'LE SSERAFIM'), ('ILLIT', 'ILLIT'), ('KISS_OF_LIFE', 'KISS OF LIFE'), ('HEARTS2HEARTS', 'Hearts2Hearts'), ('RIIZE', 'RIIZE'), ('BTS', 'BTS'), ('SEVENTEEN', 'SEVENTEEN'), ('TWS', 'TWS'), ('THE_BOYZ', 'THE BOYZ'), ('EXO', 'EXO'), ('NCT_WISH', 'NCT WISH'), ('NCT_DREAM', 'NCT DREAM'), ('ENHYPEN', 'ENHYPEN'), ('NCT_127', 'NCT 127'), ('STRAY_KIDS', 'Stray Kids'), ('TXT', 'TOMORROW X TOGETHER'), ('ZEROBASEONE', 'ZEROBASEONE'), ('ATEEZ', 'ATEEZ'), ('ASTRO', 'ASTRO'), ('N_FLYING', 'N.Flying'), ('BOYNEXTDOOR', 'BOYNEXTDOOR'), ('MONSTA_X', 'MONSTA X'), ('82MAJOR', '82MAJOR'), ('AND_TEAM', '&TEAM'), ('KICKFLIP', 'KickFlip'), ('PLAVE', 'PLAVE'), ('TREASURE', 'TREASURE')], max_length=50, null=True, verbose_name='최애 그룹')),
                ('bias_member', models.CharField(blank=True, choices=[('지수', '지수'), ('제니', '제니'), ('로제', '로제'), ('리사', '리사'), ('카리나', '카리나'), ('지젤', '지젤'), ('윈터', '윈터'), ('닝닝', '닝닝'), ('안유진', '안유진'), ('가을', '가을'), ('레이', '레이'), ('원영', '원영'), ('리즈', '리즈'), ('이서', '이서'), ('미연', '미연'), ('민니', '민니'), ('소연', '소연'), ('우기', '우기'), ('슈화', '슈화'), ('나연', '나연'), ('정연', '정연'), ('모모', '모모'), ('사나', '사나'), ('지효', '지효'), ('미나', '미나'), ('다현', '다현'), ('채영', '채영'), ('쯔위', '쯔위'), ('민지', '민지'), ('하니', '하니'), ('다니엘', '다니엘'), ('해린', '해린'), ('혜인', '혜인'), ('아이린', '아이린'), ('슬기', '슬기'), ('웬디', '웬디'), ('조이', '조이'), ('예리', '예리'), ('사쿠라', '사쿠라'), ('채원', '채원'), ('윤진', '윤진'), ('카즈하', '카즈하'), ('은채', '은채'), ('윤아', '윤아'), ('민주', '민주'), ('모카', '모카'), ('원희', '원희'), ('이로하', '이로하'), ('쥴리', '쥴리'), ('나띠', '나띠'), ('벨', '벨'), ('하늘', '하늘'), ('지우', '지우'), ('카르멘', '카르멘'), ('유하', '유하'), ('스텔라', '스텔라'), ('주은', '주은'), ('에이나', '에이나'), ('이안', '이안'), ('예온', '예온'), ('성찬', '성찬'), ('원빈', '원빈'), ('쇼타로', '쇼타로'), ('은석', '은석'), ('소희', '소희'), ('앤톤', '앤톤'), ('RM', 'RM'), ('진', '진'), ('슈가', '슈가'), ('제이홉', '제이홉'), ('지민', '지민'), ('뷔', '뷔'), ('정국', '정국'), ('에스쿱스', '에스쿱스'), ('정한', '정한'), ('조슈아', '조슈아'), ('준', '준'), ('호시', '호시'), ('원우', '원우'), ('우지', '우지'), ('디에잇', '디에잇'), ('민규', '민규'), ('도겸', '도겸'), ('승관', '승관'), ('버논', '버논'), ('디노', '디노'), ('신유', '신유'), ('도훈', '도훈'), ('영재', '영재'), ('한진', '한진'), ('지훈', '지훈'), ('경민', '경민'), ('상연', '상연'), ('제이콥', '제이콥'), ('영훈', '영훈'), ('현재', '현재'), ('주연', '주연'), ('케빈', '케빈'), ('뉴', '뉴'), ('큐', '큐'), ('선우', '선우'), ('에릭', '에릭'), ('수호', '수호'), ('시우민', '시우민'), ('디오', '디오'), ('백현', '백현'), ('찬열', '찬열'), ('카이', '카이'), ('세훈', '세훈'), ('시온', '시온'), ('리쿠', '리쿠'), ('유우시', '유우시'), ('재희', '재희'), ('료', '료'), ('사쿠야', '사쿠야'), ('마크', '마크'), ('런쥔', '런쥔'), ('제노', '제노'), ('해찬', '해찬'), ('재민', '재민'), ('천러', '천러'), ('지성', '지성'), ('정원', '정원'), ('희승', '희승'), ('제이', '제이'), ('제이크', '제이크'), ('성훈', '성훈'), ('선우', '선우'), ('니키', '니키'), ('쟈니', '쟈니'), ('태용', '태용'), ('유타', '유타'), ('도영', '도영'), ('재현', '재현'), ('윈윈', '윈윈'), ('정우', '정우'), ('마크', '마크'), ('해찬', '해찬'), ('방찬', '방찬'), ('리노', '리노'), ('창빈', '창빈'), ('현진', '현진'), ('한', '한'), ('필릭스', '필릭스'), ('승민', '승민'), ('아이엔', '아이엔'), ('연준', '연준'), ('수빈', '수빈'), ('범규', '범규'), ('태현', '태현'), ('휴닝카이', '휴닝카이'), ('성한빈', '성한빈'), ('김지웅', '김지웅'), ('장하오', '장하오'), ('석매튜', '석매튜'), ('김태래', '김태래'), ('리키', '리키'), ('김규빈', '김규빈'), ('박건욱', '박건욱'), ('한유진', '한유진'), ('성화', '성화'), ('홍중', '홍중'), ('윤호', '윤호'), ('여상', '여상'), ('산', '산'), ('민기', '민기'), ('우영', '우영'), ('종호', '종호'), ('MJ', 'MJ'), ('진진', '진진'), ('차은우', '차은우'), ('문빈', '문빈'), ('라키', '라키'), ('윤산하', '윤산하'), ('이승협', '이승협'), ('차훈', '차훈'), ('김재현', '김재현'), ('유회승', '유회승'), ('서동성', '서동성'), ('성호', '성호'), ('리우', '리우'), ('명재현', '명재현'), ('태산', '태산'), ('이한', '이한'), ('운학', '운학'), ('셔누', '셔누'), ('민혁', '민혁'), ('기현', '기현'), ('형원', '형원'), ('주헌', '주헌'), ('아이엠', '아이엠'), ('조성일', '조성일'), ('윤예찬', '윤예찬'), ('남성모', '남성모'), ('황성빈', '황성빈'), ('박석준', '박석준'), ('김도균', '김도균'), ('케이', '케이'), ('후마', '후마'), ('니콜라스', '니콜라스'), ('의주', '의주'), ('유마', '유마'), ('조', '조'), ('하루아', '하루아'), ('타키', '타키'), ('마키', '마키'), ('계훈', '계훈'), ('아마루', '아마루'), ('동화', '동화'), ('주왕', '주왕'), ('민제', '민제'), ('케이주', '케이주'), ('동현', '동현'), ('예준', '예준'), ('노아', '노아'), ('밤비', '밤비'), ('은호', '은호'), ('하민', '하민'), ('최현석', '최현석'), ('지훈', '지훈'), ('요시', '요시'), ('준규', '준규'), ('윤재혁', '윤재혁'), ('아사히', '아사히'), ('도영', '도영'), ('하루토', '하루토'), ('박정우', '박정우'), ('소정환', '소정환')], max_length=50, null=True, verbose_name='최애 멤버')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='전화번호')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='주소')),
                ('state', models.IntegerField(choices=[(0, '관리자'), (1, '일반 사용자'), (2, '숨김 사용자'), (3, '차단된 사용자')], default=1, verbose_name='사용자 상태')),
                ('manners_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='매너 온도')),
                ('nickname', models.CharField(max_length=100, unique=True, verbose_name='닉네임')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='프로필 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최근 수정일')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=100, verbose_name='선호 스타일')),
                ('idol', models.CharField(max_length=100, verbose_name='선호 아이돌')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 선호 정보',
                'verbose_name_plural': '사용자 선호 정보 목록',
            },
        ),
        migrations.CreateModel(
            name='UserRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('FOLLOW', '관심 사용자'), ('BLOCK', '차단한 사용자')], max_length=10, verbose_name='관계 유형')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_relations', to='accounts.user', verbose_name='관계 시작 사용자')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_relations', to='accounts.user', verbose_name='관계 대상 사용자')),
            ],
            options={
                'verbose_name': '사용자 관계',
                'verbose_name_plural': '사용자 관계 목록',
                'unique_together': {('from_user', 'to_user', 'relation_type')},
            },
        ),
    ]
