# Generated by Django 5.2.1 on 2025-06-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idol',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='선호 아이돌'),
        ),
        migrations.AddField(
            model_name='user',
            name='style',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='선호 스타일'),
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
