# Generated by Django 5.2.1 on 2025-06-24 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_idol_user_style_delete_userpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='idol',
        ),
        migrations.RemoveField(
            model_name='user',
            name='style',
        ),
    ]
