# Generated by Django 5.2.1 on 2025-06-24 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_idol_remove_user_style'),
        ('idols', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bias_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fans_group', to='idols.group', verbose_name='최애 그룹'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bias_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fans_member', to='idols.member', verbose_name='최애 멤버'),
        ),
    ]
